M48
; DRILL file KiCad 10.0.6 date 2026-10-08T23:49:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-08T23:49:13+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X29.11Y-6.2
X34.89Y-6.2
T2
X5.5Y-56.33
X8.5Y-56.33
M30
